variables:
  SYSDIG_SECURE_ENDPOINT: "https://secure.sysdig.com"
  CI_REGISTRY_HOST: "docker.io"
  CI_REGISTRY_NAME: "my-registry"
  CI_IMAGE_NAME: "my-image"
  CI_IMAGE_TAG: "my-tag"

stages:
  - build
  - scan
  - push

image:build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor --dockerfile Dockerfile --destination $CI_REGISTRY_HOST/$CI_REGISTRY_NAME/$CI_IMAGE_NAME:$CI_IMAGE_TAG --no-push --oci-layout-path $(pwd)/build/ --tarPath $(pwd)/build/$CI_IMAGE_TAG.tar
  artifacts:
    paths:
      - build/
    expire_in: 1 days

image:scan:
  stage: scan
  image: 
    name: sysdiglabs/secure-inline-scan:2
    entrypoint: [""]
  script:
    - mkdir reports
    - /sysdig-inline-scan.sh --sysdig-token $SYSDIG_SECURE_TOKEN  --sysdig-url $SYSDIG_SECURE_ENDPOINT --storage-type oci-dir --storage-path $(pwd)/build/ $CI_REGISTRY_NAME/$CI_IMAGE_NAME:$CI_IMAGE_TAG --report-folder reports
  artifacts:
    paths:
      - reports
      - build/
    expire_in: 1 days
  needs:
    - image:build

image:push:
  stage: push
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_HOST
    - crane push build/$CI_IMAGE_TAG.tar $CI_REGISTRY_HOST/$CI_REGISTRY_NAME/$CI_IMAGE_NAME:$CI_IMAGE_TAG
  needs:
    - image:scan
